// AUTO-GENERATED by scripts/gen_sdk_reference.py — do not edit by hand.
// Source: py-genlayer v0.2.16, pin 1jb45aa8ynh2a9c9xn3b7qqh8sm5q93hwfp7jqmwsfhh8jpz09h6
// Generated: 2026-05-12T20:52:49Z
// To regenerate: pnpm gen:sdk-reference

export const SDK_REFERENCE_HASH = "1jb45aa8ynh2a9c9xn3b7qqh8sm5q93hwfp7jqmwsfhh8jpz09h6";
export const SDK_REFERENCE_VERSION = "v0.2.16";

export const SDK_REFERENCE: string = `## SDK reference (py-genlayer v0.2.16, pin 1jb45aa8…)

The following is the curated public surface for the pinned py-genlayer release. **Any identifier not listed here does not exist.** Use this as the authoritative API surface. The hard rules and common bugs above teach idiom and gotchas; this section is the truth about what exists.

\`gl\` is a proxy to \`genlayer.gl\`. \`gl.message\`, \`gl.vm\`, \`gl.eq_principle\`, \`gl.nondet\`, \`gl.storage\` are the namespaces you'll touch most often. \`gl.Address\`, \`gl.TreeMap\`, integer widths, etc. are the same objects as the top-level imports from \`from genlayer import *\`.

### Things that do NOT exist (common hallucinations)
- \`gl.vm.timestamp()\`, \`gl.block.timestamp\`, \`gl.now()\` — there is no time API. The only time signal is \`gl.message_raw['datetime']\` (ISO-8601 string; parse with \`datetime.fromisoformat\`). **\`gl.message.datetime\` does NOT exist** — \`gl.message\` is a NamedTuple with only \`contract_address\`, \`sender_address\`, \`origin_address\`, \`value\`, \`chain_id\`.
- \`Address.zero()\`, \`Address.null()\`, \`Address.empty()\` — only \`Address(val: str | bytes)\`.
- \`@allow_storage\` on \`Enum\` — Enums aren't storage-eligible; store the \`.value\` as \`u256\`.
- \`float\` anywhere in storage or types — there is no float in the SDK type system.

### gl.message  (NamedTuple — attribute access)
\`gl.message\` is a NamedTuple with **only** these fields. Anything else (datetime, is_init, stack, entry_kind, …) lives on \`gl.message_raw\` and must be read with dict syntax — see below.

- \`contract_address: Address\`    # Address of current Intelligent Contract
- \`sender_address: Address\`    # Address of this call initiator
- \`origin_address: Address\`    # Entire transaction initiator
- \`value: u256\`
- \`chain_id: u256\`    # Current chain ID

### gl.message_raw  (TypedDict — dict access, \`gl.message_raw['field']\`)
Full transaction context as a TypedDict. **Use bracket notation, not attribute access**: \`gl.message_raw['datetime']\`, not \`gl.message_raw.datetime\`.

- \`contract_address: Address\`    # Address of current Intelligent Contract
- \`sender_address: Address\`    # Address of this call initiator
- \`origin_address: Address\`    # Entire transaction initiator
- \`stack: list[Address]\`    # Stack of view method calls, excluding last (\`\`contract_address\`\`)
- \`value: u256\`
- \`datetime: str\`    # Transaction datetime. For \`\`#get-schema\`\` it can be some predefined datetime
- \`is_init: bool\`    # \`\`True\`\` *iff* it is a deployment
- \`chain_id: u256\`    # Current chain ID
- \`entry_kind: int\`    # One of
- \`entry_data: bytes\`
- \`entry_stage_data: calldata.Encodable\`

### gl.vm  (VM utilities)
Errors, sandboxing, and the nondet primitives.

- \`class Return\` (dataclass)    # Represents a successful return value from a VM operation.
    - calldata: T    # Decoded return value from the VM execution
- \`class VMError\` (dataclass)    # Represents an error that occurred within the VM during execution.
    - message: str    # Description of the VM error that occurred. It begins with code, such as \`\`exit_code\`\`
- \`class UserError\` (dataclass)    # Represents an error that user contract rose during execution of their code in the VM.
    - message: str    # User-provided message. Be careful to use concise message, as by default they are checked for strict equality
- \`unpack_result(res: Result[T], /) -> T\`    # The actual return value if successful
- \`spawn_sandbox(fn: typing.Callable[[], T], *, allow_write_ops: bool = False) -> Lazy[Return[T] | VMError | UserError]\`    # Runs a function in an isolated sandbox environment.
- \`run_nondet_unsafe(leader_fn: typing.Callable[[], T], validator_fn: typing.Callable[[Result], bool], /) -> Lazy[T]\`    # The result from the leader (iff validation passes, otherwise VM will be terminated)
- \`run_nondet(leader_fn: typing.Callable[[], T], validator_fn: typing.Callable[[Result[T]], bool], /, *, compare_user_errors: typing.Callable[[UserError, UserError], bool] = lambda a, b: a.message == b.message, compare_vm_errors: typing.Callable[[VMError, VMError], bool] = lambda a, b: a.message == b.message) -> Lazy[T]\`    # The result from the leader if validation passes
- \`type Result[T] = Return[T] | VMError | UserError\`    # union of VM outcomes

### gl.eq_principle  (consensus wrappers)
Wrap every \`gl.nondet.*\` call (including hash and web) in one of these.

- \`strict_eq(fn: typing.Callable[[], T]) -> Lazy[T]\`    # Comparative equivalence principle that checks for strict equality
- \`prompt_comparative(fn: typing.Callable[[], T], principle: str) -> Lazy[T]\`    # Comparative equivalence principle that utilizes NLP for verifying that results are equivalent
- \`prompt_non_comparative(fn: typing.Callable[[], str], *, task: str, criteria: str) -> Lazy[str]\`    # Non-comparative equivalence principle that must cover most common use cases

### gl.nondet  (non-deterministic primitives — ALWAYS wrap in eq_principle)

- \`gl.nondet.exec_prompt(prompt: str, **config: typing.Unpack[ExecPromptKwArgs]) -> Lazy[str | dict]\`    # API to execute a prompt (perform NLP)

**gl.nondet.web** (HTTP requests + headless render):
- \`gl.nondet.web.str_or_bytes_to_bytes(data: str | bytes | None) -> bytes | None\`
- \`gl.nondet.web.get(url: str, *, headers: dict[str, str | bytes] = {}) -> Lazy[Response]\`
- \`gl.nondet.web.post(url: str, *, body: str | bytes | None = None, headers: dict[str, str | bytes] = {}) -> Lazy[Response]\`
- \`gl.nondet.web.delete(url: str, *, body: str | bytes | None = None, headers: dict[str, str | bytes] = {}) -> Lazy[Response]\`
- \`gl.nondet.web.head(url: str, *, body: str | bytes | None = None, headers: dict[str, str | bytes] = {}) -> Lazy[Response]\`
- \`gl.nondet.web.patch(url: str, *, body: str | bytes | None = None, headers: dict[str, str | bytes] = {}) -> Lazy[Response]\`
- \`gl.nondet.web.request(url: str, *, method: typing.Literal['GET', 'POST', 'DELETE', 'HEAD', 'OPTIONS', 'PATCH'], body: str | bytes | None = None, headers: dict[str, str | bytes] = {}) -> Lazy[Response]\`
- \`gl.nondet.web.render(url: str, *, mode: typing.Literal['html', 'text', 'screenshot'] = 'text', wait_after_loaded: str | None = None) -> Lazy[str | Image]\`    # API to get a webpage after rendering it in a browser-like environment

**gl.nondet.hash**: \`keccak256(data: bytes) -> bytes\` (and similar). All hash calls live in \`gl.nondet.hash\` and need \`eq_principle.strict_eq\` wrapping.

### Address  (also available as \`gl.Address\`)
- \`__init__(self, val: str | collections.abc.Buffer)\`
    - \`.as_bytes: bytes\`    # raw bytes of an address (most compact representation)
    - \`.as_hex: str\`    # checksum string representation
    - \`.as_b64: str\`    # base64 representation of an address (most compact string)
    - \`.as_int: u160\`    # int representation of an address (unsigned little endian)
- **No** \`Address.zero()\`, \`Address.null()\`, \`Address.empty()\` etc. exist. For an all-zero sentinel use \`Address("0x" + "00" * 20)\`.

### Integer types  (from \`genlayer.py.types\`, also under \`gl.*\`)
- Unsigned: \`u8, u16, u24, u32, u40, u48, u56, u64, u72, u80, u88, u96, u104, u112, u120, u128, u136, u144, u152, u160, u168, u176, u184, u192, u200, u208, u216, u224, u232, u240, u248, u256\`
- Signed:   \`i8, i16, i24, i32, i40, i48, i56, i64, i72, i80, i88, i96, i104, i112, i120, i128, i136, i144, i152, i160, i168, i176, i184, i192, i200, i208, i216, i224, i232, i240, i248, i256\`
- Unbounded: \`bigint\`
- **No floats anywhere in the SDK** — there is no \`float\` storage descriptor and no float type alias.
- Construct as \`u256(123)\`, \`i64(-1)\`, \`bigint(10**40)\`.

### Storage primitives (\`from genlayer import *\` or \`gl.storage\`)

**Eligible storage types** (the SDK rejects anything else):
- \`Address\`, \`str\`, \`bytes\`, \`bool\`, \`None\`
- Every integer width above (\`u8…u256\`, \`i8…i256\`, \`bigint\`)
- \`TreeMap[K, V]\`, \`DynArray[T]\`, \`Array[T, N]\`
- \`@allow_storage\`-decorated dataclasses or plain classes
- **\`Enum\` subclasses are NOT eligible.** Store the underlying integer (\`u256(MyEnum.X.value)\`) and round-trip via the Enum class inside methods.

- \`gl.storage.inmem_allocate(t: typing.Type[T], *init_args, **init_kwargs) -> T\`
- \`gl.storage.copy_to_memory(val: T) -> T\`
- \`@allow_storage\` decorator — apply to dataclasses / plain classes used as storage field types or inside generic containers.

**TreeMap[K, V]** — ordered map; keys must be \`Comparable\`. Methods:
- \`tree.clear(self)\`
- \`tree.compute_if_absent(self, k: K, supplier: typing.Callable[[], V]) -> V\`    # Value associated with \`k\` if it is present, otherwise get's new value from the supplier, stores it at \`k\` and returns
- \`tree.get_or_insert_default(self, k: K) -> V\`
- \`tree.get(self, k: K, /, default = None)\`    # Value associated with \`k\` or \`default\` if there is no such value
- \`tree.items(self) -> collections.abc.ItemsView[K, V]\`
- Plus the usual mapping interface: \`m[k]\`, \`m[k] = v\`, \`del m[k]\`, \`k in m\`, \`iter(m)\`, \`len(m)\`.

**DynArray[T]** — growable list:
- \`arr.insert(self, index: int, value: T) -> None\`
- \`arr.append(self, value: T) -> None\`
- \`arr.append_new_get(self) -> T\`
- \`arr.pop(self) -> None\`
- \`arr.clear(self) -> None\`
- Plus the usual sequence interface: \`arr[i]\`, \`arr[i] = v\`, \`iter(arr)\`, \`len(arr)\`.

**Array[T, N]** — fixed-size array. Indexing only; no append/pop. \`N\` is a literal integer type-parameter.

### Pointer-only namespaces
These exist but their surface isn't enumerated inline. If you need them, refer to the SDK source on disk.
- \`gl.evm.*\` — Ethereum bridge primitives (see \`genlayer/gl/evm/\`).
- \`gl.events.*\` — \`Event\` class and emission helpers (\`genlayer/gl/events.py\`).
- \`gl.advanced.*\` — escape hatches; rarely needed.
- \`gl.calldata\` — calldata encode/decode helpers.
- \`gl.contract_interface\`, \`gl.get_contract_at(addr)\`, \`gl.deploy_contract(...)\` — contract-to-contract calls.
- \`gl.Lazy[T]\` — used as return type of eq_principle / nondet wrappers; resolve with \`.get()\` if needed.
`;
